FROM rust:slim as base
WORKDIR /usr/src/aot-backend
RUN apt-get update -y && apt-get install -y libpq-dev netcat
RUN cargo install cargo-chef

FROM base as planner
COPY . .
RUN cargo chef prepare --recipe-path recipe.json

FROM base
COPY --from=planner /usr/src/aot-backend/recipe.json recipe.json
RUN cargo chef cook --release --recipe-path recipe.json
COPY . .
RUN cargo build --release
